export const messageTitleSuccesCreditApplication = "Crédito solicitado"
export const messageContentSuccesCreditApplication = "Crédito solicitado, ahora puedes ver el estado en tu lista de solicitudes"
export const messageErrorCeditApplication = "Error al solicitar crédito"
export const messageContentErrorCeditApplication = "Ocurrió un error al solicitar el crédito"
export const errorMessageCreditApplicationCancel = "Ocurrió un error al cancelar el crédito, porfavor vuelve a intentarlo"
export const errorTitleMessageCreditApplicationCancel = "Error al cancelar el crédito"
export const messageTitleSuccessCancelCreditoApplication = "Crédito Cancelado"
export const messageContentSuccessCancelCreditApplication = "Crédito cancelado exitosamente" 